module.exports = {
  spacingsMap: {
    'p': ['padding'],
    'py': ['padding-top', 'padding-bottom'],
    'px': ['padding-left', 'padding-right'],
    'pt': ['padding-top'],
    'pl': ['padding-left'],
    'pr': ['padding-right'],
    'pb': ['padding-bottom'],
    'm': ['margin'],
    'my': ['margin-top', 'margin-bottom'],
    'mx': ['margin-left', 'margin-right'],
    'mt': ['margin-top'],
    'ml': ['margin-left'],
    'mr': ['margin-right'],
    'mb': ['margin-bottom'],
    'w': ['width'],
    'h': ['height'],
    'max-w': ['max-width'],
    'max-h': ['max-height'],
    'inset': ['top', 'left', 'right', 'bottom'],
    'inset-y': ['top', 'bottom'],
    'inset-x': ['left', 'right'],
    'top': ['top'],
    'left': ['left'],
    'right': ['right'],
    'bottom': ['bottom'],
    'gap': ['gap'],
    'gap-y': ['row-gap'],
    'gap-x': ['column-gap'],
    'translate': ['translate'],
    'translate-x': ['translateX'],
    'translate-y': ['translateY'],
    'border-spacing': ['border-spacing'],
    'border-spacing-x': ['border-spacing'],
    'border-spacing-y': ['border-spacing'],
  },
  borderRadiusesMap: {
    '': ['border-radius'],
    't': ['border-top-left-radius', 'border-top-right-radius'],
    'l': ['border-top-left-radius', 'border-bottom-left-radius'],
    'r': ['border-top-right-radius', 'border-bottom-right-radius'],
    'b': ['border-bottom-right-radius', 'border-bottom-left-radius'],
    'tl': ['border-top-left-radius'],
    'tr': ['border-top-right-radius'],
    'br': ['border-bottom-right-radius'],
    'bl': ['border-bottom-left-radius']
  }
}
